import '@modules/utils/observer'
import '@modules/utils/scroll-amimate'
import '@modules/utils/scroll'
import '@modules/utils/mobile-menu'
import '@modules/utils/swiper'
import '@modules/popups/popups'
import '@modules/test/test'
import '@modules/products/products'
